apiVersion: v1
kind: Service
metadata:
  name: {{ include "techtrends.fullname" . }}
  labels:
    {{- include "techtrends.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.appName }}
