apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
spec:
  ports:
  - port: 4111
    protocol: TCP
    targetPort: 3111
  ## Identify the pods managed by this Service using the following selectors.
  ## In this case, all pods with the label `go-helloworld`.
  selector:
    app: techtrends
  ## Define the Service type, here set to ClusterIP.
  type: ClusterIP
