appName: techtrends

namespace:
  name: sandbox

replicaCount: 1

image:
  repository: nightmar39/techtrends
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  containerPort: 3111 
  livenessPath: healthz
  readinessPath: healthz

service:
  type: ClusterIP
  port: 4111
  targetPort: 3111
  protocol: TCP 

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi